// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "Calculadora.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



CalculadoraApp::Calculadora_ptr CalculadoraApp::Calculadora_Helper::_nil() {
  return ::CalculadoraApp::Calculadora::_nil();
}

::CORBA::Boolean CalculadoraApp::Calculadora_Helper::is_nil(::CalculadoraApp::Calculadora_ptr p) {
  return ::CORBA::is_nil(p);

}

void CalculadoraApp::Calculadora_Helper::release(::CalculadoraApp::Calculadora_ptr p) {
  ::CORBA::release(p);
}

void CalculadoraApp::Calculadora_Helper::marshalObjRef(::CalculadoraApp::Calculadora_ptr obj, cdrStream& s) {
  ::CalculadoraApp::Calculadora::_marshalObjRef(obj, s);
}

CalculadoraApp::Calculadora_ptr CalculadoraApp::Calculadora_Helper::unmarshalObjRef(cdrStream& s) {
  return ::CalculadoraApp::Calculadora::_unmarshalObjRef(s);
}

void CalculadoraApp::Calculadora_Helper::duplicate(::CalculadoraApp::Calculadora_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

CalculadoraApp::Calculadora_ptr
CalculadoraApp::Calculadora::_duplicate(::CalculadoraApp::Calculadora_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

CalculadoraApp::Calculadora_ptr
CalculadoraApp::Calculadora::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


CalculadoraApp::Calculadora_ptr
CalculadoraApp::Calculadora::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

CalculadoraApp::Calculadora_ptr
CalculadoraApp::Calculadora::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Calculadora _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Calculadora* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Calculadora;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* CalculadoraApp::Calculadora::_PD_repoId = "IDL:CalculadoraApp/Calculadora:1.0";


CalculadoraApp::_objref_Calculadora::~_objref_Calculadora() {
  
}


CalculadoraApp::_objref_Calculadora::_objref_Calculadora(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::CalculadoraApp::Calculadora::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
CalculadoraApp::_objref_Calculadora::_ptrToObjRef(const char* id)
{
  if (id == ::CalculadoraApp::Calculadora::_PD_repoId)
    return (::CalculadoraApp::Calculadora_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::CalculadoraApp::Calculadora::_PD_repoId))
    return (::CalculadoraApp::Calculadora_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for CalculadoraApp::Calculadora::calculate

// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_cdouble_i_cdouble_i_cstring
class _0RL_cd_fdaffc4393d29375_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_fdaffc4393d29375_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  ::CORBA::Double arg_1;
  ::CORBA::String_var arg_2_;
  const char* arg_2;
  ::CORBA::Double result;
};

void _0RL_cd_fdaffc4393d29375_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;
  _n.marshalString(arg_2,0);

}

void _0RL_cd_fdaffc4393d29375_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;
  (::CORBA::Double&)arg_1 <<= _n;
  arg_2_ = _n.unmarshalString(0);
  arg_2 = arg_2_.in();

}

void _0RL_cd_fdaffc4393d29375_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_fdaffc4393d29375_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_fdaffc4393d29375_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_fdaffc4393d29375_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_fdaffc4393d29375_00000000* tcd = (_0RL_cd_fdaffc4393d29375_00000000*)cd;
  CalculadoraApp::_impl_Calculadora* impl = (CalculadoraApp::_impl_Calculadora*) svnt->_ptrToInterface(CalculadoraApp::Calculadora::_PD_repoId);
  tcd->result = impl->calculate(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

::CORBA::Double CalculadoraApp::_objref_Calculadora::calculate(::CORBA::Double valor1, ::CORBA::Double valor2, const char* operacao)
{
  _0RL_cd_fdaffc4393d29375_00000000 _call_desc(_0RL_lcfn_fdaffc4393d29375_10000000, "calculate", 10);
  _call_desc.arg_0 = valor1;
  _call_desc.arg_1 = valor2;
  _call_desc.arg_2 = operacao;

  _invoke(_call_desc);
  return _call_desc.result;


}

CalculadoraApp::_pof_Calculadora::~_pof_Calculadora() {}


omniObjRef*
CalculadoraApp::_pof_Calculadora::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::CalculadoraApp::_objref_Calculadora(ior, id);
}


::CORBA::Boolean
CalculadoraApp::_pof_Calculadora::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::CalculadoraApp::Calculadora::_PD_repoId))
    return 1;
  
  return 0;
}

const CalculadoraApp::_pof_Calculadora _the_pof_CalculadoraApp_mCalculadora;

CalculadoraApp::_impl_Calculadora::~_impl_Calculadora() {}


::CORBA::Boolean
CalculadoraApp::_impl_Calculadora::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "calculate")) {

    _0RL_cd_fdaffc4393d29375_00000000 _call_desc(_0RL_lcfn_fdaffc4393d29375_10000000, "calculate", 10, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
CalculadoraApp::_impl_Calculadora::_ptrToInterface(const char* id)
{
  if (id == ::CalculadoraApp::Calculadora::_PD_repoId)
    return (::CalculadoraApp::_impl_Calculadora*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::CalculadoraApp::Calculadora::_PD_repoId))
    return (::CalculadoraApp::_impl_Calculadora*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
CalculadoraApp::_impl_Calculadora::_mostDerivedRepoId()
{
  return ::CalculadoraApp::Calculadora::_PD_repoId;
}

POA_CalculadoraApp::Calculadora::~Calculadora() {}

