// This file is generated by omniidl (C++ backend)- omniORB_4_3. Do not edit.
#ifndef __Calculadora_hh__
#define __Calculadora_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_Calculadora
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_Calculadora
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_Calculadora
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CalculadoraApp

_CORBA_MODULE_BEG

#ifndef __CalculadoraApp_mCalculadora__
#define __CalculadoraApp_mCalculadora__
  class Calculadora;
  class _objref_Calculadora;
  class _impl_Calculadora;
  
  typedef _objref_Calculadora* Calculadora_ptr;
  typedef Calculadora_ptr CalculadoraRef;

  class Calculadora_Helper {
  public:
    typedef Calculadora_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Calculadora, Calculadora_Helper> Calculadora_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Calculadora,Calculadora_Helper > Calculadora_out;

#endif

  // interface Calculadora
  class Calculadora {
  public:
    // Declarations for this interface type.
    typedef Calculadora_ptr _ptr_type;
    typedef Calculadora_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Calculadora :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Double calculate(::CORBA::Double valor1, ::CORBA::Double valor2, const char* operacao);

    // Constructors
    inline _objref_Calculadora()  { _PR_setobj(0); }  // nil
    _objref_Calculadora(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Calculadora();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Calculadora(const _objref_Calculadora&);
    _objref_Calculadora& operator = (const _objref_Calculadora&);
    // not implemented

    friend class Calculadora;
  };

  class _pof_Calculadora : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Calculadora() : _OMNI_NS(proxyObjectFactory)(Calculadora::_PD_repoId) {}
    virtual ~_pof_Calculadora();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Calculadora :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Calculadora();

    virtual ::CORBA::Double calculate(::CORBA::Double valor1, ::CORBA::Double valor2, const char* operacao) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_CalculadoraApp
_CORBA_MODULE_BEG

  class Calculadora :
    public virtual CalculadoraApp::_impl_Calculadora,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Calculadora();

    inline ::CalculadoraApp::Calculadora_ptr _this() {
      return (::CalculadoraApp::Calculadora_ptr) _do_this(::CalculadoraApp::Calculadora::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CalculadoraApp
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
CalculadoraApp::Calculadora::_marshalObjRef(::CalculadoraApp::Calculadora_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_Calculadora
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_Calculadora
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_Calculadora
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_Calculadora
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_Calculadora
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_Calculadora
#endif

#endif  // __Calculadora_hh__

