FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    omniorb-nameserver \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 2809

CMD ["omniNames", "-start", "-ORBendPointPublish", "giop:tcp::2809"]